### ISSUE TITLE
Introducción al Java VisualVM

### ISSUE THREAD

**Issue by SergioMartinezP** [javamexico/propuestas-meetup#12]
Mostrar algunos ejemplos de como utilizar Java Visual VM para ayudar a encontrar problemas en aplicaciones corriendo en el JVM
- ¿Qué es Java Visual VM?
- ¿Cómo me conecto a un JVM?
- Plugin para observar el comportamiento del GC
- Ejemplo de revisión de memoria
- Ejemplo de revisión de código

**Comment by chuucks** [comment]
Suena muy interesante...!

**Comment by mxd4n13l0n** [comment]
Estaría genial para darle continuidad al #11
