### ISSUE TITLE
Alta disponibilidad de microservicios REST con Docker

### ISSUE THREAD

**Issue by arellano-gustavo** [javamexico/propuestas-meetup#14]
Durante esta plática crearemos una imagen Docker vía "Dockerfile".
Mostraremos cómo modificarlo y hacer commit de los cambios, generando de esta forma una nueva imagen.
Mostraremos cómo guardarlo en DockerHub.
Usaremos la imagen creada para levantar cuatro instancias de un microservicio (java-spring-springboot previamente creado) en cuatro distintos puertos de un mismo host.
Configuraremos HAProxy para que distribuya la carga entrante entre los distintos Dockers usando una estrategia de round-robin.
Comentaremos cómo crear un repositorio Docker local.
Comeremos Pizza y beberemos Cerveza !

**Comment by laliux** [comment]
Hola @arellano-gustavo 

Puedes dar esta charla en este mes ? la fecha del meetup es el 29 de Agosto.

Saludos

**Comment by arellano-gustavo** [comment]
Hola Eduardo !!!

Claro que si.
Te gustaría llamarme para ponernos de acuerdo?
O prefieres que te marque?
Mi Cel es 55 16913070

Saludos,
Gustavo


2016-08-16 12:23 GMT-05:00 Eduardo Zarate <notifications@github.com>:

**Comment by laliux** [comment]
Hola Gustavo,

Ya tus compañeros me pasaron tu correo, te envié un mail hace rato. 

Saludos

**Comment by DjSystemBPM** [comment]
como le hago para votar Gus

**Comment by arellano-gustavo** [comment]
Te debería salir un icono con símbolo de "like" (mano amarilla) No lo logras ver?

**Comment by DjSystemBPM** [comment]
No
