### ISSUE TITLE
JShell y REPL

### ISSUE THREAD

**Issue by j49u4r** [javamexico/propuestas-meetup#18]
La propuesta es una charla-taller acerca de **JShell**:

- ¿Qué es?
- ¿Cuál es su origen?
- ¿Cuál es su propósito y/o aplicaciones?
- Ejercicios que incluyen Streams desde el JShell

Algo sobre mí: Augusto Alonso (j49u4r), soy un tanto nuevo con Java (3 años). Actualmente trabajo con el lenguaje en el lado de backend y disfruto lo que hago.

No olviden votar por el tema. Saludos!!!

**Comment by laliux** [comment]
Hola j49u4r,

Cuánto tiempo tienes pensado que te puede llevar este taller ? 

Saludos

**Comment by j49u4r** [comment]
Hola,

Considero que entre 1 hora y 1:15.

Saludos!

**Comment by laliux** [comment]
Súper,

Podrías el lunes 24 o el miércoles 26 de este mes ? En el horario habitual, de 7:30 a 9:30..

**Comment by j49u4r** [comment]
Cualquiera de estas dos fechas me parecen bien. Tú organízate y me avisas.

👍

**Comment by laliux** [comment]
Perfecto. Te aviso.

**Comment by j49u4r** [comment]
Sí, claro. Quedo al pendiente.

Gracias!

**Comment by arellano-gustavo** [comment]
Ojala pueda ser el Lunes.

**Comment by laliux** [comment]
Confirmado, será el lunes 24.

En un momento publico el evento.

Saludos.

PD. No faltes @arellano-gustavo , con toda tu banda!

**Comment by laliux** [comment]
@j49u4r  tienes cuenta de twitter ? me la pasas porfa...

**Comment by j49u4r** [comment]
@augustojimenez1

**Comment by j49u4r** [comment]
Eduardo voy en camino, algo de tráfico(mucho), llego 25min, disculpa

On Oct 13, 2016 12:24 PM, "Domingo Suarez Torres" <notifications@github.com>
wrote:

Assigned #18 <https://github.com/javamexico/propuestas-meetup/issues/18> to
@j49u4r <https://github.com/j49u4r>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/javamexico/propuestas-meetup/issues/18#event-822838349>,
or mute the thread
