### ISSUE TITLE
¿Por qué Cassandra?

### ISSUE THREAD

**Issue by rugi** [javamexico/propuestas-meetup#19]
Entre toda la oferta NoSQL que existe en el mercado, Apache Cassandra aparece como una de las opciones más robustas ( y quizá también poco conocidas).
El objetivo de la charla es darle respuesta a la pregunta que encabeza esta descripción, platicaremos del protocolo que usa por dentro y de las bondades que ofrece para tener un ambiente HA, daremos por supuesto un breve, muy breve, repaso de la naturaleza NoSQL .

Su integración con **Spark** y con otros _frameworks_ de desarrollo la hace una opción atractiva.
Si estás diseñando tu stack de desarrollo y  aún no te decides por un NoSQL,, esta plática puede ayudarte a decidir.
## Sobra decir.... corre sobre la JVM ;)

RuGI

**Comment by laliux** [comment]
@rugi habrá chance de mover charla -> taller de 3 o 4 horas ?

Así lo podemos abrir en sábado como en ocasiones anteriores.

Saludos

**Comment by rugi** [comment]
Pues, tendría que generar el material... pero , sin problema.
Sólo tendríamos que ver fechas, pero, eso ya es por otros canales ;)

**Comment by rugi** [comment]
La charla se convirtió en taller 👍
