### ISSUE TITLE
JVM Reactive Programming

### ISSUE THREAD

**Issue by domix** [javamexico/propuestas-meetup#2]
Mostrar como se puede hacer programación reactiva en la JVM.

Se usaria código vivo con RxJava con Java y Groovy

**Comment by abadongutierrez** [comment]
con que frameworks o lenguajes?

**Comment by neburnz** [comment]
La plática podría ser teórica y unos ejemplos usando [Rx-Java](https://github.com/ReactiveX/RxJava)
Aquí encontré algunos [slides](http://www.slideshare.net/kasun04/reactive-programming-in-java-8-with-rxjava)

**Comment by domix** [comment]
ya actualice la descripción @abadongutierrez, te parece bien o agrego algo mas?
