### ISSUE TITLE
Creación de servicios RESTful con Jersey

### ISSUE THREAD

**Issue by chuucks** [javamexico/propuestas-meetup#20]
# Creación de servicios RESTful con Jersey
### Justificación

En la actualidad la creación de Servicios RESTful es muy útil para el consumo desde clientes web, móvil, de escritorio o Stand Alone. Con la API nativa de Java EE: JAX-RS podemos lograrlo. Pero, cómo hacemos para hacer más flexible y eficiente este proceso? La solución es el framework Open Source: Jersey.
### Sumario

Charla sobre el framework Jersey, hablaremos un poco de su configuración, implementación, sus capacidades y ventajas, además de algunos casos de éxito en mi carrera profesional.
### Outline

**1. Presentación**
- Breve relato de mi carrera y experiencia
- Muestra de algunos ejemplos de mi trabajo y proyectos

**2. Planteamiento**
- Relevancia de los Servicios REST en la actualidad
- Uso de Servicios RESt en ambientes corporativos
- Ventajas de integrar Jersey

**3. Implementación y Resultados**
- Configuración
- Implementación
- Mejoras en rendimiento

**4.- Conclusiones**
- Casos convenientes en los cuales implementarlo
- Casos de éxito
## Fecha tentativa

Cualquier fecha en la que el equipo de JVM MX lo considere conveniente está perfecto.
## Acerca de mí

**Nombre**: Carlos Salazar (Chuuck)
**URL**: [Portafolio](https://codesolt.com/)
**Blog**: [Blog](https://codesolt.com/java)
**Pic**: [Dando una charla Central](https://codesolt.com/assets/img/resume/who-we-are-image-3.jpg)
**Bio**: "Ingeniero de Software por la UNAM, desarrollador Web en AVON, escritor en Platzi y fundador de Codesolt. Antes desarrollador de Software en Scotiabank"
**Ejemplo de charla**: [Clase de Scrum en Platzi](https://platzi.com/clases/comunidad-platzi/concepto/estrategia/ventajas-de-usar-scrum/material/)
**mail**: carlos.salazar@codesolt.com
### Adicional

Gracias por leer este ISSUE (propuesta de charla), espero poder compartir con la comunidad muy pronto, soy fiel seguidor de JVM Mx. Un especial saludo! :)

**Comment by laliux** [comment]
Se ve bastante interesante, ojalá ganes los suficientes votos para el meetup de Noviembre. El de octubre ya está cubierto :)

Saludos

**Comment by rugi** [comment]
Se ve de alto poder!
Quizá si le agregas: _como documentar_, puedas _amarrar_ el contenido y mostrar el ciclo completo.
Felicitaciones.

**Comment by dev2me** [comment]
Genial :)

**Comment by EmmanuelRoman** [comment]
Suena bastante interesante y en lo personal aún no he podido trabajar o conocer más a profundidad los servicios RESTFUL.

**Comment by laliux** [comment]
Hola @chuucks 

Tenemos agendado el meetup de noviembre para el día miércoles 23. 

¿Puedes?

Saludos

**Comment by chuucks** [comment]
Claro @laliux :) 
Por favor déjenme saber cualquier cosa adicional que requieran de mi parte.
Saludos!
