### ISSUE TITLE
Workshop: Database refactoring

### ISSUE THREAD

**Issue by neodevelop** [javamexico/propuestas-meetup#21]
Este workshop pretende mostrar como puedes versionar y modificar tu base de datos de forma controlada, así como, conservar la integridad de los datos.

Breve agenda:
- ¿Qué es el refactor de BD?
- Primer esquema
- Modificando y creando tablas
- Partiendo relaciones
- Creando llaves
- Transportando datos
- Tags y rollbacks

La tecnología a usar sería Liquibase y pos ya...

**Comment by chuucks** [comment]
Suena potencial, ojalá se concrete... 🚶
