### ISSUE TITLE
Arquitecturas de despliegue: #microservices #serverless

### ISSUE THREAD

**Issue by domix** [javamexico/propuestas-meetup#22]
La idea es que @chochos @rugi @domix @SergioMartinezP  discutan sobre estas arquitecturas y reciban preguntas de los asistentes

1. Que diversas opciones existen para deployment
  * Clásicas de #godinezjvm (AppServer mamalón tipo WebSphere, Weblogic, etc)
  * millenials #microservicios #serverless
  * contenedores (Docker, rkt, rancher, kubernetes, mesos, etc)
  * Cloud (Amazon, Google, Heroku)
2. Pros y contras

**Comment by chochos** [comment]
Yo me apunto

**Comment by domix** [comment]
# Mesa de discusión o debate

La idea es que @chochos @rugi @domix discutan sobre estas arquitecturas y reciban preguntas de los asistentes

**Comment by rugi** [comment]
Va.

**Comment by SergioMartinezP** [comment]
Suena bien!

**Comment by rugi** [comment]
Microservicio y serverless son 2 de los términos que más han dominado este año.
Una estrategia de implantación no es sencilla e implica ciertos riesgos que no siempre vemos.
Puede ser una charla muy enriquecedora para todos, tanto para los que ya los están usando, para los que están iniciando, para los que aun no se deciden e incluso para los detractores.

Será que ya existen las <balas de plata>?
Voten!
Se pondrá bueno el show ;)

**Comment by isccarrasco** [comment]
Wow... por lo que veo soy del team #godinezjvm (usando actualmente Wildfly) ... aunque he intentado algo con Docker... a ver para que fecha queda el evento ;)

**Comment by domix** [comment]
No te veo votando @isccarrasco

**Comment by CypraxPuch** [comment]
Ser punta de lanza en cualquier tecnología implica grandes retos, como el de ser el primero que se enfrenta a las fallas, errores, excepciones, etc. y tener que lidiar con estas!!! 
Tenemos la opción de ser punta de lanza o seguir con paradigmas bien probados (léase viejos).

**Comment by rugi** [comment]
@CypraxPuch por supuesto, y es genial llegar a buen puerto después de pasar por todo eso :)
A quien no le gusta se héroe!

El tema justamente es platicar sobre el "ELSE" de ese IF.
Quizá no sea tan buena idea ser punta de lanza cuando lo que quieres mover es el core de tu negocio o, no tienes a la gente lista/preparada.
Lo viejo no es malo, si logra pasar la estafeta a lo nuevo de una manera correcta.
Esperamos verte ese día :D

**Comment by CypraxPuch** [comment]
buen tema @rugi!! 
no pienso perdérmelo!!!
Saludos!!

**Comment by rugi** [comment]
Nos vemos!!
Ahora nomas que quede la fecha 😄

**Comment by blzb** [comment]
y si corro weblogic en docker en que categoria entra? http://www.oracle.com/us/products/middleware/cloud-app-foundation/weblogic/weblogic-server-on-docker-wp-2742665.pdf

**Comment by domix** [comment]
Entra en #HipsterGodinezDeLaJVM @blzb 
![image](https://cloud.githubusercontent.com/assets/21805/19990426/30a9bd72-a1f3-11e6-990e-099d208d3454.png)

**Comment by jsramos** [comment]
Me ganaron con el "mamalón"! Jajaja! Una constelación al frente!

**Comment by CypraxPuch** [comment]
@domix yo diría que @blzb entra mas en la categoría de #chavorukoJVM!! xD

**Comment by blzb** [comment]
Cabe aclarar que no es mi caso @CypraxPuch, solo preguntaba en que categoria entraba ese caso.

**Comment by CypraxPuch** [comment]
Nada personal mr.

**Comment by code-bomb** [comment]
@domix excelente propuesta!!!  use OAS, ahora WL11g  y próximamente WL12c  #godinezjvm

**Comment by rugi** [comment]
@blzb curiosamente, a pesar de ese _soporte_ oficial a docker, WL quiere manejar a su manera el aislamiento de procesos con lo nuevo de la versión 12:
Multitenant.

Desde su trinchera, cada sector busca como cumplir con lo mismo.
Yo veo 3 puntos principales:

- Aislamiento de procesos
- Optimización de recursos
- Facilitar la administración de lo que esos dos puntos anteriores generan.

Entre otras cosas.

**Comment by arcioneo** [comment]
Para cuando es esta?
Soy nuevo y no veo fechas, gracias de antemano.

**Comment by isccarrasco** [comment]
@arcioneo aún no se ha definido la fecha, hay algunas otras charlas en cola según he entendido

**Comment by laliux** [comment]
Hola a todos,

No se ha definido la fecha, esperamos que pueda realizarse en este Diciembre para cerrar con tocho un gran año.

Saludos

**Comment by arellano-gustavo** [comment]
Se ve bueno. Cuando sera?

**Comment by laliux** [comment]
Hola a todos, no tenemos fecha definida, pero seguro en este Diciembre ya no fue. Queremos que se haga en Enero, esperemos que así sea.

Saludos

**Comment by chochos** [comment]
Bueno esto fue ayer así que lo cerramos, pero esperamos feedback aquí mismo.
