### ISSUE TITLE
Términos y "modas" en el desarrollo de aplicaciones con la JVM

### ISSUE THREAD

**Issue by malcantara** [javamexico/propuestas-meetup#23]
La finalidad de éste issue es invitar a la comunidad a participar en charla/debate/panel dónde se den a conocer y se analicen términos y "modas" utilizados hoy en día como lo son "microservicios", "serverless", "containerization", "Paas", "Fass", "Saas", y su relación con el desarrollo de aplicaciones dentro del ecosistema de la JVM.

Esta invitación esta abierta a todo aquel que quiera participar con su conocimiento y experiencia.

**Comment by domix** [comment]
esto suena a un panel no @benek ?

**Comment by benek** [comment]
Sí estaría de huevos!

**Comment by benek** [comment]
Panel realizado el pasado 13 de octubre.

Link en Youtube: https://youtu.be/auzRjBhRU8o
