### ISSUE TITLE
Flow: tipado estatico en javascript

### ISSUE THREAD

**Issue by Ikana** [javamexico/propuestas-meetup#29]
Javascript es la lingua franca de la web y hay ocasiones que por requerimientos o por capricho del cliente hay que usarlo, la queja mas fuerte que escucho al platicar con los miembros de la comunidad de java, es que, javascript es un lenguaje con un tipado débil, que solo falla en tiempo de ejecución y una gran parte de la comunidad de javascript que nos dedicamos full time a JS estamos de acuerdo.

En el espíritu de intercambiar ideas entre varias comunidades, propongo dar un charla sobre [flow](https://flow.org/).

### Sumario

Platicare sobre flow un sistema de tipado estático para JS, con inferencia de tipos, tipos union, tipos intersección y que que aunque puede ser usado stand alone, es desarrollado por un equipo interno de facebook para facilitar el desarrollo de todo su ecosistema (react, react-native, graphql ...)

### Outline

1. Tipos en vanilla JS
2. Pequeña historia sobre flow
3. Tipos en flow
4. Inferencia de tipos
5. Tipos union
6. Tipos intersección
7. Features avanzados de flow
8. Libreria standart de flow
9. Liberias externas y flow-typed
10. Pequeño boilerplate

**Comment by loydiux** [comment]
Aquí una botella!
