### ISSUE TITLE
JVM & Docker

### ISSUE THREAD

**Issue by SergioMartinezP** [javamexico/propuestas-meetup#3]
Introducción a Docker y algunos casos de como desplegar aplicaciones Java en Docker

**Comment by GloriaPG** [comment]
+ 100 💃

**Comment by SergioMartinezP** [comment]
La idea será comentar como Docker Engine formó parte del http://repositorionacionalcti.mx 

- ¿Qué es Docker?
- Características del porqué usar Docker
- Detalles a considerar al agregar un JVM a Docker
- Agregando Payara Micro y JavaEE 7
- HAProxy al frente de todos (SSL terminator)
- Siguientes pasos
- Preguntas

**Comment by GloriaPG** [comment]
Estaría muy padre! Yo voto por que sí.
