### ISSUE TITLE
RESTful Web Service con Reactive Spring

### ISSUE THREAD

**Issue by raphaelDL** [javamexico/propuestas-meetup#33]
Charla en que hablaremos de aplicaciones asincronas no-bloqueantes con Spring 5 (que implementa reactive-streams).
El enfoque reactive permite optimizar el uso de los recursos y facilita que las aplicaciones escalen verticalmente.
Mostraremos de ejemplo un servicio REST utilizando Spring Framework 5, Boot 2.0 y Data MongoDB 2.0

**Comment by laliux** [comment]
Hola @raphaelDL 

Pásame por fa' tus datos de contacto: eduardo AT bbfour DOT com.

Saludos
