### ISSUE TITLE
Modelo de Actores en Java: Akka

### ISSUE THREAD

**Issue by hiphoox** [javamexico/propuestas-meetup#35]

**Comment by rvazquezglez** [comment]
Hace un tiempo hice un par de presentaciones, por si te sirven:
* https://docs.google.com/presentation/d/1kCrlDn_LZE3f0VXQOIWE1Y7h9HD3YLjwDOPMGF47sJc/edit?usp=sharing
* https://docs.google.com/presentation/d/1HEN-pohcmpkGuxkh6XtScxmFWVzyhgofJOk1YQy6Rv8/edit?usp=sharing

**Comment by domix** [comment]
Disfrute mucho la charla, aunque hubiera sido interesante ver mas sobre el modelo de actores, saber la experiencia sobre Akka es valioso sin duda.
