### ISSUE TITLE
Apache Beam: Aventuras en la consistencia eventual

### ISSUE THREAD

**Issue by dominoFire** [javamexico/propuestas-meetup#36]
En esta plática mostraremos las experiencias con Apache Beam / Google Cloud Dataflow, el marco de trabajo para unificar tareas de procesamiento en batch y en streaming. También, mostraremos un ejemplo de cómo se podría ocupar Apache Beam / Google Cloud Dataflow para un simple pipeline de ETL. Finalmente, discutiremos por qué es muy importante tomar las semánticas de consistencia a la hora de diseñar sistemas distribuidos (web).

**Comment by laliux** [comment]
Hola @dominoFire 

Aún está en pie lo de tu charla ? Podrías el lunes 26 de Marzo ?

Saludos

**Comment by mrduckieduck** [comment]
¿Qué paso con esta platica?

**Comment by benek** [comment]
Cerrado por inactividad.
