### ISSUE TITLE
Más allá de REST con gRPC

### ISSUE THREAD

**Issue by domix** [javamexico/propuestas-meetup#37]
La idea de la charla es mostrar las bondades de usar gRPC en favor de REST

**Comment by Ikana** [comment]
Solo para comunicacíon entre microservicios? o crees que tambien se peude aplicar para comunicacíon con el cliente?

**Comment by domix** [comment]
Si con el cliente te refieres a JS en el browser, voy a mostrar el gateway REST para lograr eso.

**Comment by crusillo2003** [comment]
Me gustaria escuchar esta charla. Saludos!!
