### ISSUE TITLE
Vert.x Core

### ISSUE THREAD

**Issue by neburnz** [javamexico/propuestas-meetup#4]
Como el tema es amplio por la cantidad de extensiones, sugiero acotarlo al uso del Core.
Si existe algún experto en el tema que pueda mostrar algunos casos donde sea conveniente usar Vert.x.

**Comment by chochos** [comment]
> Si existe algún experto en el tema...

O sea que estás pidiendo que alguien más dé esta plática? La idea que si abres un issue es porque **tú** quieres dar la charla que propones...

**Comment by neburnz** [comment]
Ok, gracias por la aclaración. Aún no soy experto en el tema pero la noche es larga y el café barato. Lo tendré en consideración para la próxima. ;)

**Comment by chochos** [comment]
Pero entonces, no pensabas dar esta charla tú? para cerrar el issue en ese caso...

**Comment by neburnz** [comment]
Creo que es mejor cerrar el issue en lo que domino el tema, y mejor sugerir algún otro.
