### ISSUE TITLE
Cómo evitar que un proyecto de 13 años se vuelva legacy

### ISSUE THREAD

**Issue by chochos** [javamexico/propuestas-meetup#40]
El proyecto donde más tiempo he trabajado, tiene ya 13 años. Comenzó en Java 1.4 y actualmente se está actualizando a Java 8. Ha pasado por varias versiones de varios frameworks, varias reestructuraciones, muchos cambios, para evitar que se vuelva algo _legacy_.

La idea de esta charla es contar a manera de anécdota, los cambios que se han hecho a este proyecto para poder mantenerlo actualizado durante tanto tiempo, y cómo seguir manteniéndolo así.

**Comment by rugi** [comment]
Realizada en el meetup de Mayo del 2018
https://www.meetup.com/jvm-mx/events/250882991/
Se grabó la sesión en la página de Facebook de javaMéxico.
