### ISSUE TITLE
Project Lombok

### ISSUE THREAD

**Issue by chuucks** [javamexico/propuestas-meetup#41]
# Reduce el código repetitivo y aumenta las capacidades de tus POJOs con anotaciones simples

## Justificación
El código repetitivo en nuestros POJOs sule ser cansado de generar y en la mayoría de las veces delegamos esta tarea al editor de nuestro IDE. La desventaja es que generamos clases difíciles de leer y mantener.

Con las anotaciones de Project Lombok, podemos crear POJOs más elegantes y fáciles de leer, además de aumentar sus capacidades. Sin duda una biblioteca muy simple pero muy poderosa que me ha resultado de gran utilidad en mis proyectos.

## Agenda
1. Necesidades de un código más limpio.
2. Introducción al projecto de código abierto Lombok.
3. Configuración de las anotaciones en nuestras clases.
4. Funcionamiento (la "magia" detrás de Lombok).
5. Integración con otras bibliotecas para POJOs.
6. Ejecución en un proyecto real.
7. Conclusiones

## Fecha tentativa
Finales de Enero o finales de Febrero me viene bien, charla de apox. 30 min.
_Ahora vivo en Guadalajara, una confirmación anticipada me facilitaría planear mi traslado._

## Acerca de mí
**Nombre**: Carlos Salazar
**Portafolio**: https://carlos-salazar.com
**Blog**: https://codesolt.com
**Bio**: Desarrollador Java en HP, fundador de Codesolt, co-organizador de JUG Gdl.
**Experiencia Charla**: Speaker en la JUG de Montreal, Canada (http://www.montreal-jug.org/meetup/spring-security-oauth/)
**Ejemplo Charla**: https://www.youtube.com/watch?v=vGsMoD0hLUc

## Contacto
Mail: carlos.salazar@codesolt.com
Twitter: @ chuucksc

**Comment by chochos** [comment]
Por qué cerraron esta propuesta?

**Comment by laliux** [comment]
Pues la cerró el mismo @chuucks  :/
