### ISSUE TITLE
[Clash of boots] Demostrar como haces en la vida real servicios HTTP RPC (REST que le dicen)

### ISSUE THREAD

**Issue by domix** [javamexico/propuestas-meetup#42]
La idea es que varias personas, demuestren en 15 (chance 20) minutos máximo, como usan `Spring Boot` para hacer aplicaciones que exponen servicios HTTP RPC (aka `REST`).

Cada expositor debería poder mostrar:

1. Configuración de la herramienta de construcción, mencionar los plugins que usan y para que.
2. Modularización (si aplica)
3. Persistencia (SQL y/o NoSQL)
4. Contratos de API
5. Pruebas
6. Contenedores (si usan y como los usan)
7. Integración Continua, deseable CD

Creo que con 3 o 4 máximo personas, se puede mostrar un abanico interesante.

**Comment by chuucks** [comment]
Hola @domix cuenten conmigo si requieren de una opinión sobre el uso de Spring Boot para creación de servicios Rest en un ambiente corporativo (corriendo sobre Red Hat o Windows Server) cc @chochos @domix Saludos! :)

**Comment by josechval** [comment]
Lo hago con Flask en 10. :D

**Comment by hguerrero** [comment]
Cuenten conmigo, podemos mostrar como trabajar con SB, Apache Camel y Kubernetes (Red Hat Flavored)

**Comment by pedrooshika-nomad** [comment]
si tienen un poco de paciencia con un brasileño hablando español mal (o si puedo hablar en inglés) puedo presentar detalles de la plataforma en que trabajo (iFood, el player brasileño de food delivery, líder en américa latina, y que está detrás de SinDelantal.mx)

hoy tenemos una plataforma con ~70 (micro) servicios (casi todos en java / spring- *)

**Comment by domix** [comment]
claro que si @poshika, el requisito es que el api este escrito en `Spring Boot`

**Comment by pedrooshika-nomad** [comment]
ah sí, claro, por `spring- *` quiero decir spring-boot, web, mvc, data, security, etc! :)

**Comment by edgarh2e** [comment]
Cuenten conmigo para compartir mi experiencia con `Spring Boot`, `Swagger `, `Jersey` sobre `AWS Elastic Beanstalk`.

**Comment by laliux** [comment]
Hola @chuucks @hguerrero @poshika @edgarh2e @domix 

Cómo andan el lunes 30 de abril ? Tienen chance de asistir y participar en el meetup de ese día?

Saludos

**Comment by domix** [comment]
yo sin problema @laliux

**Comment by edgarh2e** [comment]
@laliux cuenten conmigo.

**Comment by hguerrero** [comment]
me parece bien! cuenten conmigo.

**Comment by laliux** [comment]
Perfecto @domix @edgarh2e @hguerrero ,

Pues con ustedes 3 ya la hicimos, publico el evento de una vez.

@chuucks @poshika siguen invitados, sólo confirmen si van.

Saludos

**Comment by chuucks** [comment]
Hola @laliux justo el 30 de Abril ando por Cd Mx, sería increíble poder compartir con ustedes ese día ;)
Solo les pediría confirmar qué específicamente (dentro del tema de microservicios) abarcaremos.

Saludos desde Guadalajara! :)

**Comment by chuucks** [comment]
Update: ya vi los temas que se van a tocar en el evento de meetup.com, cuenten conmigo.

**Comment by laliux** [comment]
@chuucks genial! acá te esperamos..

**Comment by pedrooshika-nomad** [comment]
perdon @laliux , estaba de vaccaciones y volvi hoy.
y no voy a poder participar mañana, no estoy en Mexico! :(
