### ISSUE TITLE
Actualización del OWASP Top 10

### ISSUE THREAD

**Issue by SergioMartinezP** [javamexico/propuestas-meetup#43]
cada 3~4 años se actualiza la lista de los 10 principales riesgos en aplicaciones web por lo que sería conveniente dar un repaso a la versión del 2017

**Comment by rugi** [comment]
Realizada en el meetup de Mayo del 2018
https://www.meetup.com/jvm-mx/events/250882991/
Se grabó la sesión en la página de Facebook de javaMéxico.
