### ISSUE TITLE
GraalVM: Porque puede existir una VM poliglota, incrustable y eficiente

### ISSUE THREAD

**Issue by domix** [javamexico/propuestas-meetup#44]
La idea de la charla es introducir mediante ejemplos prácticos las 3 características de `GraalVM`

* Poliglota: Ejecutar múltiples lenguajes (No solo aquellos que generan `byte code` para la `JVM`)
* Incrustable: Mostrar como se puede usar `GraalVM` de forma incrustada.
* Eficiente: Ver los tiempos de ejecución pueden optimizarse en producción considerablemente.

**Comment by laliux** [comment]
Presentada el lunes 28 de enero de 2019.
