### ISSUE TITLE
Lightning talk: Un gran poder de código, conlleva una gran JVM

### ISSUE THREAD

**Issue by lgbaeza** [javamexico/propuestas-meetup#46]
A través de esta Lightning talk quisiera compartirles algo de lo que más me aqueja: terminar mi código y tener que desplegarlo en una aplicación. Porque seamos honestos, a todos nos gusta programar, ese bonito arte de poder materializar algo creado apenas unos momentos antes en nuestra cabeza; Pero cuando hay que utilizar gestores de versiones, trabajar con CD/CI, o inclusive publicar en sitios externos con toda la instalación de bibliotecas, conectores y demás que eso implique, la cosa no se pone tan buena.
Ojalá les resulte interesantes algunas de las buenas prácticas que quiero compartirles.

Luis Baeza, Developer advocate en IBM México. Ha asesorado a casi un centenar de empresas en el uso de tecnologías como Cloud, AI, IoT y Blockchain, así como en mejores prácticas de desarrollo: DevOps, Agile.

**Comment by laliux** [comment]
Hola @lgbaeza 

Tienes chance de dar esta plática el próximo lunes 27 de agosto?

Saludos

**Comment by lgbaeza** [comment]
Hola @laliux  Si, con gusto.

**Comment by laliux** [comment]
Genial @lgbaeza  ,

Bueno, te agendamos. Me puedes pasar tus datos de contacto por correo? e.zarate.m AT gmail DOT com


Gracias
