### ISSUE TITLE
Ya es momento de migrar a Java 8 o 9 o 10 u 11 :O !!!

### ISSUE THREAD

**Issue by j49u4r** [javamexico/propuestas-meetup#47]
La charla se trata de instar a la comunidad a usar ya, las características de Java 8; además de comentar las bondades que Java 9 y Java 10 ofrecen. Por último, informar acerca de las características de Java 11, la nueva "cadencia" de liberaciones de Oracle en cuanto al JDK se refiere, así como la política de soporte LTS.

- Intro a características de Java 8, 9 y 10
- Refactorización de código con Java 8
- Demostración de mejoras en Java 9
- Revisión de características de Java 10 (Local variable type inference, entre otras)
- Qué hay de Java 11

Es importante recalcar que el énfasis es animar a la comunidad que aun no lo ha hecho, a usar ya Java 8.

**Comment by rugi** [comment]
Muy buena propuesta!
Duda.... 
¿Adicional al formato de charla, ves viable tener una versión extendida para ser expuesta como taller?
Que bueno que te animaste!

**Comment by j49u4r** [comment]
Hola. Sí, veo viable esa posibilidad.

Saludos!

**Comment by laliux** [comment]
Hola @j49u4r 

Tienes chance de dar esta charla para el meetup de este mes ? .. lunes 29.

o.O
