### ISSUE TITLE
Patrones de diseño en diferentes lenguajes de la JVM

### ISSUE THREAD

**Issue by rvazquezglez** [javamexico/propuestas-meetup#5]
**de qué vas a hablar?** 
Un overview de patrones de diseño OO y alternativas en diferentes lenguajes:
http://slides.com/rvazquezglez/write-less-code-and-overcome-oo-with-functional-features/

**cuál es el objetivo,** 
Conocer de forma general patrones de diseño y algunas alternativas en diferentes lenguajes de la JVM

**una bio corta**
Desarrollador Java at Nearsoft

**Comment by abadongutierrez** [comment]
Que diferentes lenguajes?

**Comment by rvazquezglez** [comment]
Scala, Groovy, Clojure y Java, dependiendo del patrón

**Comment by chochos** [comment]
A la mera hora ya no hubo nada de Clojure?

Buena charla en general.
