### ISSUE TITLE
Microservicios - Orquestación VS Coreografía

### ISSUE THREAD

**Issue by jivel** [javamexico/propuestas-meetup#53]
¿Alguien está utilizado  [ **Conductor**](https://netflix.github.io/conductor/) para la orquestación de Microservicios?

¿Cuál es la opinion que tienen de  [**Camunda**](https://camunda.com/) para comunicar los Microservicios?

¿Qué herramientas están utilizando para comunicar sus Microservicios?

**Comment by mrduckieduck** [comment]
:)

**Comment by benek** [comment]
@jivel ha pasado buen tiempo, ¿sigue vigente tu propuesta?

**Comment by benek** [comment]
Cerrado por inactividad.
