### ISSUE TITLE
Amazon Alexa, NLU y desarrollo de apps de Voz con Java

### ISSUE THREAD

**Issue by softwarechido** [javamexico/propuestas-meetup#56]
Hace un par de meses lancé junto con mi equipo de trabajo el Servicio de Alexa en México: 

https://developer.amazon.com/blogs/alexa/post/d5614e27-99d2-460b-a295-51f4fde36f89/

Ahora mi trabajo es compartir con el mundo lo que hemos logrado e inspirar a desarrolladores de todo el mundo a crear experiencias de voz extraordinarias con Alexa en Español.

Actualmente la capacidad de computo distribuido nos ha permitido evolucionar el procesamiento natural del lenguaje a niveles de precisión nunca antes visto. En una arquitectura de microservicios, esta nueva forma de interactuar con las computadoras nos hace replantear la forma como diseñamos nuestros servicios de front end y siembra la semilla para un nuevo tipo de interfaces de voz que llamo: Voice end.

Para mi un Voice End no es otra cosa mas que un nuevo tipo de componente en la capa de presentación, una especia de front end de Voz que permite a nuestros usuarios interactuar con nuestros servicios via comandos hablados. En esta charla exploro el poder de los servicios de AWS: Alexa voice Service y AWS Lambda, explico la anatomía de una skill (voice first apps) y algunas consideraciones para desarrollar los servicios de AWS para soportar una skill.

**Comment by rugi** [comment]
Charla realizada en el meetup del 29 de Abril del 2019.
https://www.meetup.com/jvm-mx/events/260540788/
