### ISSUE TITLE
Quarkus 

### ISSUE THREAD

**Issue by aukustomx** [javamexico/propuestas-meetup#57]
Anunciado en la pasada DevNexus, la intención es dar a conocer Quarkus, el framework by Red Hat que promete ser Cloud and Container First (k8s), sus características y ventajas, y cómo podemos aprovecharlo para la implementación de microservicios.

Ojo, aun no hay versión Production-Grade, pero "va que zumba pa' allá".

**Comment by laliux** [comment]
Se dió la charla en meetup de  Septiembre 2019.
