### ISSUE TITLE
Generando una API con Open API Spec 2.0 y Swagger

### ISSUE THREAD

**Issue by yobijoss** [javamexico/propuestas-meetup#58]
José Ángel García Salinas

Soy backend dev @ Kenzan, mi camino me ha llevado a aprender y compartir sobre el mundo backend. Esta (sería) es mi 4ta charla en Guadalajara. 

En esta charla usaremos Java 8, Spring boot y Swagger para generar una API con base en la Open API Specification version 2.0

**Comment by chuucks** [comment]
Charla para el meetup virtual *
