### ISSUE TITLE
Revisión del sistema de módulos 

### ISSUE THREAD

**Issue by eduvim** [javamexico/propuestas-meetup#59]
Revisión de usos prácticos del sistema de módulos y sus integraciones con herramientas cómo Maven y Gradle. Revisión teórica + live coding

**Comment by aukustomx** [comment]
Sistema de módulos Java9+ ?

**Comment by eduvim** [comment]
Si , ese mero sistema de módulos

**Comment by laliux** [comment]
Hola @eduvim 

Podrías dar tu charla este mes?.. lunes 24 de junio..

o.O

**Comment by eduvim** [comment]
Vale , te sería útil que lo mande previo para revisión ? 

Si podría estar listo

**Comment by laliux** [comment]
@eduvim 

Genial, pues queda amarrado. Mándame un correo a e.zarate.m en gmail punto com.

Gracias!

**Comment by rugi** [comment]
Se concretó en la reunión de Junio del 2019
https://www.meetup.com/jvm-mx/events/262400795/
