### ISSUE TITLE
Descubriendo las lambdas

### ISSUE THREAD

**Issue by xiumeteo** [javamexico/propuestas-meetup#6]
de qué vas a hablar? 
Una desconstrucción de los lambdas y cómo están implementadas en Java 8, hablaré un poco de invokedynamic, bootstrap method, y el ciclo de ejecución de una lambda

cuál es el objetivo, 
entender un poco más acerca de cómo están implementadas las lambdas en Java 8 

una bio corta
Desarrollador Java at Nearsoft

**Comment by rvazquezglez** [comment]
Estaría chido ver el contexto de uso, donde ocupar lambdas? como simplificar clases anónimas a lambdas

**Comment by xiumeteo** [comment]
@rvazquezglez estoy de acuerdo pero creo que por el tiempo el tema que mencionas puede dar para una plática en si misma :)

**Comment by chochos** [comment]
Buena charla, aunque algo densa la última parte de hacer tu propio Bootstrap. Más que si se puede o no se puede, a veces hay que preguntarse, para qué?
