### ISSUE TITLE
Tools to monitor JVM

### ISSUE THREAD

**Issue by breakponchito** [javamexico/propuestas-meetup#64]
Houston tenemos un problema!!!!

La memoria se está yendo al límite que debemos hacer, espera déjame llamó al ingeniero java

Llega el ingeniero java: permíteme dejame evaluarlo

Tengo un abanico de herramientas que me pueden apoyar:

- Jconsole
- Visualvm
- JMC
- Etc ….

En el día a día tenemos situaciones inesperadas que debemos evaluar de momento y tenemos que utilizar las herramientas que nos den la información necesaria que nos permita obtener un diagnostico y así poder encontrar una solución al problema. En esta presentación observaremos varias opciones que nos pueden ayudar a identificar situaciones que debemos atender para que nuestras aplicaciones puedan mantenerse siempre activas

Acerca de mi:
Mi nombre es Alfonso Valdez Altamirano y soy un ingeniero con 14 años de experiencia trabajando en diversos sectores: educación, gobierno, telecomunicaciones, financiero, servicios, fintech, e-commerce. Además cuento con 9 certificaciones de oracle que me han ayudado a mantener un nivel de calidad en los servicios que proporciono y actualmente trabajo para Globant proporcionando servicios a un cliente fintech de California

**Comment by domix** [comment]
gracias @breakponchito, por favor podrías elaborar más tu propuesta. Es para metup presencial o virtual?

**Comment by breakponchito** [comment]
Si para el virtual, me intereso que fuera en ese modelo pero también podría
ser presencial sin problema

**Comment by breakponchito** [comment]
El día de mañana agrego mas detalle a la presentación que propuse presentar

**Comment by domix** [comment]
me puedes mandar un email a domingo.suarez@gmail.com @breakponchito por favor?

**Comment by laliux** [comment]
@breakponchito creo que esto quedó en el tintero,.. aún estás interesado y en la posibilidad de dar la charla?

Saludos

**Comment by benek** [comment]
Cerrado por inactividad.
