### ISSUE TITLE
Spring Cloud Config

### ISSUE THREAD

**Issue by blzb** [javamexico/propuestas-meetup#7]
Configuracion externalizada para ambientes distribuidos.

Explorar las caracteristicas de la libreria y formas de usarlo.

**Comment by laliux** [comment]
Hola que tal,..

Oye, tenemos agendada la fecha del 26 de octubre para el siguiente meetup.

Te queda ese día ? podrías dar tu charla para esa fecha?

Saludos

**Comment by laliux** [comment]
Hola @blzb 

Ya tenemos fecha para el meetup de noviembre. Sería el miércoles 23, puedes en esa fecha? Te anotamos?

Saludos

**Comment by blzb** [comment]
@laliux Hola, tengo ocupadas todas las tardes de lunes y miercoles lo que queda del año. Martes, jueves o viernes estoy disponible.

**Comment by laliux** [comment]
@blzb Sale, que bueno que nos dices. Podría ser el jueves 24, deja ver que onda con el otro speaker.. te aviso.

Saludos

**Comment by chuucks** [comment]
Suena buena, pero falta explicar... 🤔
