### ISSUE TITLE
Buenas prácticas para simplificar el desarrollo de software 

### ISSUE THREAD

**Issue by ipholo** [javamexico/propuestas-meetup#70]
El objetivo de la plática es dar a conocer todos las practicas que seguimos en nuestro proceso de desarrollo en Java. Desde como imaginamos el código en nuestra cabeza, se escribe, se prueba y es puesto en producción. Se tocarán temas como: 

- Guías de estilo 

- Entregables 

- Peer Reviews 

- Testing 

Todo esto en ambientes con cambios frecuentes a nivel a global.

**Comment by benek** [comment]
Cerrado debido a que la charla ya no está vigente con el ponente.
