### ISSUE TITLE
Twelve-Factor App methodology 

### ISSUE THREAD

**Issue by kodyakckaly** [javamexico/propuestas-meetup#71]
Se hablará de las "mejores practicas" diseñadas por Heroku para permitir que las aplicaciones web se creen con portabilidad y resistencia cuando se implementan en la web. 

¿Qué pasa si no tomo en cuenta estás estrategias?
El error más común es que obtienes un proyecto el cual depende de diversos recursos, y cuando un desarrollador quiere instalarlo en su ambiente todos esos recursos se pierden o colapsan por una mal configuración de la aplicación; generando a su vez tiempos altos en desarrollo. 

¿Para quién es la plática?
Cualquier persona que construya aplicaciones y las ejecute como un servicio así como las personas que desplieguen y gestionen dichas aplicaciones. (DevOps, Operaciones, desarrolladores, ingenieros en sistemas, etc.)

**Comment by laliux** [comment]
Charla impartida en meetup en línea de Abril 2020.
