### ISSUE TITLE
Desarrollo y pruebas de APIs web con Swagger

### ISSUE THREAD

**Issue by cenobyte321** [javamexico/propuestas-meetup#73]
**¿Quién soy?**

Luis Ramírez - Desarrollador de software en Koneksys

**¿De qué voy a hablar?**

Swagger es una colección herramientas bastante popular para documentar APIs y generar stubs de código para servidor y clientes.

En esta plática tocaré los siguientes temas:

- Un poco de historia de Swagger y OpenAPI
- Las herramientas principales que conforman Swagger.
- Las diferentes formas en las que podemos usar el generador de código de Swagger (Swagger Codegen).
- Los acercamientos code-first y API-spec-first.
- El diseño general de Swagger Codegen y cómo modificar el código generado.
- Diferencias entre Swagger Codegen y OpenAPI Codegen.

Mostraré cómo configurar un proyecto API con Spring MVC, Swagger Codegen y un acercamiento API-spec-first. Enseñaré cómo esta configuración puede ayudarnos a tener un proyecto API en donde sea fácil escribir pruebas automatizadas y mantener el código sincronizado con el spec de OpenAPI.

**¿Cuál es el objetivo?**

La audiencia entenderá cómo poder usar Swagger en un proyecto de Java para facilitar el desarrollo, pruebas, documentación y mantenimiento de una API web.

**Comment by benek** [comment]
@cenobyte321, recién impartiste la charla de Smart Contracts en el meetup, pero en el caso de esta, ¿aún está vigente esta propuesta?

**Comment by benek** [comment]
Cerrado por inactividad.
