### ISSUE TITLE
Desarrollo web para desarrolladores backend

### ISSUE THREAD

**Issue by alejandro-du** [javamexico/propuestas-meetup#74]
**Abstract:**
Java es una de las opciones más populares para el desarrollo de aplicaciones web. El uso de Java en el _backend_ es simple y directo. Sin embargo, la plataforma web requiere HTML y JavaScript en el _frontend_. Esto exige a los desarrolladores _full stack_ ser políglotas. Pero hay una alternativa: Vaadin–un framework para el desarrollo de interfaces de usuario web usando el lenguaje de programación Java.

Vaadin se centra en el uso Componentes Web para visualizar UIs en el navegador. Estas UIs son implementadas en Java ejecutado del lado del servidor, lo que hace la implementación de elementos de comunicación (como por ejemplo servicios web REST) completamente opcionales. Cómo es posible esto? Únete a esta charla para aprender cómo implementar UIs web en nuestro lenguaje favorito: Java!

**Alejandro Duarte** es Ingeniero de Software, [autor publicado](https://www.amazon.com/author/alejandroduarte) y Developer Relations Manager en Vaadin Ltd.

**Comment by rugi** [comment]
Realizado en el meetup de Mayo 2020. 
Virtual, derivado de la situación generada por el Covid-19.
Registro del Meetup 
https://www.meetup.com/jvm-mx/events/270736883/

Video en youTube.
https://www.youtube.com/watch?v=26-HfQ4YRAw
