### ISSUE TITLE
Mecanismos y patrones para acelerar adopción en arquitecturas de microservicios

### ISSUE THREAD

**Issue by ElderMael** [javamexico/propuestas-meetup#75]
## Sobre la charla

A traves de estos ultimos 5 años ayudando varios tipos de empresas a crear plataformas digitales basadas en microservicios he trabajado como ingeniero de plataforma, tooling y productividad ayudando a equipos de desarrolladores a adoptar dichas plataformas. 

He identificado varios mecanismos y patrones que ayudan a dichos equipos a adoptar microservicios asi como solventar problemas que aparecen cuando se requiere mantener la plataforma activa.

## Sobre Mi

Soy un consultor de TI en ThoughtWorks con 5 años de experiencia creando plataformas digitales basadas en microservicios.
Antes de eso trabaje en otras consultoras como ingeniero de infraestructura, front-end y backend.

## Slides
https://docs.google.com/presentation/d/1fi5gDJftQzYCZRVS6ZmkHDirNmPZ8zFmrTYobjtt9YQ/edit?usp=sharing

**Comment by benek** [comment]
Link a la charla, impartida el 26 de octubre de 2020: https://youtu.be/YLq3x-WtaRc
