### ISSUE TITLE
Identificando problemas en tu aplicación

### ISSUE THREAD

**Issue by SergioMartinezP** [javamexico/propuestas-meetup#77]
Di esta platica en JConfMex, y lamentablemente algunos puntos los pasé muy rápido, en un meetup podríamos extendernos un poco más y observar cada problema con dos herramientas, para poder compararlas, y tener preguntas para cada uno de los 4 casos presentados.

Las herramientas a usar son jConsole, VisualVM y Java Mission Control; todas open source y con la posibilidad de utilizarlas en producción.

Los casos a observar son:
- Memory leak
- Dead lock
- Object allocation
- Resource contention

**Comment by domix** [comment]
super si!

**Comment by viccomx** [comment]
Me encantaría!
