### ISSUE TITLE
Grails & Web Components(Polymer)

### ISSUE THREAD

**Issue by rodrigoSaladoAnaya** [javamexico/propuestas-meetup#8]
### Modalidad

_Taller_
### Duración estimada

_3 hrs._
### Break

_20 minutos._
### Descripción
1. Mostrar con un ejemplo sencillo y paso a paso las bondades de usar [Web Components](https://en.wikipedia.org/wiki/Web_Components). Voy a utilizar [Polymer](https://en.wikipedia.org/wiki/Polymer_%28library%29) aprovechando que ya tenemos la versión [1.0](https://www.polymer-project.org/1.0/) y que con esta librería podemos usar [todas las características que forman a un Web Components en la mayoría de los navegadores populares](https://www.polymer-project.org/1.0/docs/browsers).
2. Lo anterior montado sobre [Grails](https://grails.org/). Veremos como agregar la librería(Polymer) y en general mis _recomendaciones_ de donde y porque poner todos los recursos que usemos en este taller [_librerías, CSS, JS, HTML, etc._]
### Objetivo

Mostrar que las herramientas que provee Grails para la [vista](https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller) están sobrevaloradas y que la [documentación](http://docs.grails.org/latest/guide/theWebLayer.html#gsp) no es una biblia, podemos tomar otros caminos. 
### A quien va dirigido

A toda la comunidad en general, ya que voy a construir una micro-app con Grails y Polymer desde cero. Y si alguien es bien chingon con Grails y/o Polymer y quiere aportar de su conocimiento en caliente, por favor te suplico que asistas ya que si bien va a ser un taller voy a tratar que sea más como un [pair programing](https://en.wikipedia.org/wiki/Pair_programming) pero nivel [orgia](http://s33.postimg.org/mpvukzg5b/funny_dog_time.jpg).
### Requisitos y compromiso

[Grails 3.X](https://grails.org/download.html),  [Polymer 1.0](https://github.com/Polymer/polymer) y buena actitud : ). Voy a llevar la aplicación hecha; ya en github, para que si alguien se pierde en el proceso o se va más temprano tenga una referencia.
### Bio

Entusiasta programador.
[Back|Front]end.
Llevo unos 4 años trabajando con Groovy/Grails y muchos otros más con otras tecnologías.
[@rodrigo_salado](https://twitter.com/rodrigo_salado)

**Comment by AlexSnake11** [comment]
Perfecto me apunto, en donde y cuando va hacer? será un meet up?

**Comment by rodrigoSaladoAnaya** [comment]
Pues esto es solo la propuesta, aun que la redacte como si ya la fuera a dar (jo), a ver que opina la comunidad y luego ver otros factores como tiempos y espacios : ).

**Comment by sohjiro** [comment]
¡Yo también me apunto!
