### ISSUE TITLE
Vavr en la vida real

### ISSUE THREAD

**Issue by domix** [javamexico/propuestas-meetup#81]
La idea de esta charla es la de continuar la charla que tanto @mrduckieduck como @domix impartieron el año pasada de introducción a Vavr

Ahora la saga continúa para contar como el uso de esta biblioteca puede ayudar en el desarrollo de productos digitales en la vida real.

---

# Descripcion de la charla

Durante el uso de `vavr` en la vida real, hemos aprendido alternativas para manejo de errores, bien usando las estructuras de control de `vavr` como `Either`, `Try` entre otras. Así como patrones de programación objeto-funcional.

Ahora nuestro enfoque al manejar errores o tareas simples como bucles, decisiones, transformaciones se han simplicado gracias al paradigma funcional. Hemos aplicado esto a productos digitales que operan sobre millones de usuarios sin alguna dificultad.

Aun nos queda mucho camino ppr recorrer para aropvechar mas `vavr`, en una futura sesion podriamos cubrir los modelos asincronos de ejecucion de las diversas estructuras de control que posee `vavr`.

**Comment by benek** [comment]
Se impartirá para el meetup del 27 de septiembre, 2021.

**Comment by benek** [comment]
Impartida en el meetup de septiembre, 2021.

Video: https://www.youtube.com/watch?v=xd-FTaDaSlk
