### ISSUE TITLE
Whatsapp Chatbot con Geb

### ISSUE THREAD

**Issue by rodrigoSaladoAnaya** [javamexico/propuestas-meetup#84]
En esta charla estaríamos viendo como usar Geb -"Jeb"-, para crear un chatbot usando el servicio web de Whatsapp[WAPP].

La versión web de WAPP es un buen caso de uso porque tiene comportamientos que se han vuelto bastante comunes en la industria, como es: usar modificaciones dinámicas del DOM, usar un "single page application", también tiene comportamientos asíncronos, etc.

Y la idea es mostrar un poco como hacer un proceso automatizado con Geb, desde instalar el WebDriver, revisar un poco el modelo Page Object, entender cómo funciona el servicio web de WAPP y con todo eso poder implementar nuestro web scraper para crear nuestro chatbot.

Sería una sesión práctica, veremos mucho código y necesitaría del apoyo de la comunidad para que manden mensajes de WAPP a un número X para hacer la demostración el día del meetup.

Mi nombre es Rodrigo Salado Anaya, soy desarrollador de software con mucho interés en compartir con la comunidad lo poco que he usando en mi día a día laboral.

Saludos.

**Comment by rugi** [comment]
Charla impartida en el meetup de Marzo del 2022.
El video puede consultarse aquí:  https://www.youtube.com/watch?v=nH-L5eZMmpg
