### ISSUE TITLE
Java y grafos. Iniciemos con Neo4j.

### ISSUE THREAD

**Issue by rugi** [javamexico/propuestas-meetup#88]
Las bases de datos orientadas a grafos siguen avanzando de manera discreta en el día a día de las soluciones informáticas.
La intención de esta charla es:

- Recordar la importancia de una bbdd orientada a grafos.
- Ver algunos casos de uso.
- Saber por dónde empezar usando recursos gratuitos ( conoceremos un servicio gratuito de neo4j).
- Como conectarnos usando java (springboot, quarkus,  helidon, micronaut)
- Recomendar siguientes pasos.

Y listo.

**Comment by abadongutierrez** [comment]
👍

**Comment by benek** [comment]
@rugi ¿presencial o virtual? 🙂

**Comment by rugi** [comment]
> @rugi ¿presencial o virtual? 🙂

Inicialmente virtual, si el mes en que se acepte coincide con que esté en la CDMX y en ese mismo mes se tiene planeada una sesión presencial, sería presencial.

**Comment by rugi** [comment]
La URL de la presentación.
https://drive.google.com/file/d/1K0Adx7Jb1NCoUqLTXg0ceqpfvYyBbMEa/view
