### ISSUE TITLE
Spring Boot Service Connections con Testcontainers

### ISSUE THREAD

**Issue by eddumelendez** [javamexico/propuestas-meetup#92]
Spring Boot 3.1 ha sido liberado y uno de los grandes tópicos en esta versión es la integración con Testcontainers. En esta charla, revisaremos las mejoras y nuevas features agregadas para mejorar la DX.

**Comment by eddumelendez** [comment]
Julio o Agosto me queda bien 🙃

**Comment by domix** [comment]
ya podemos cerrar este no @benek?

**Comment by benek** [comment]
Sí ya, lo cierro.
