### ISSUE TITLE
Aspect Oriented Programming explained (Charla presencial)

### ISSUE THREAD

**Issue by domix** [javamexico/propuestas-meetup#93]
Un pilar fundamental de algunos frameworks de desarrollo es la Aspect Oriented Programming (AOP), herramientas como Micronaut y Spring aprovechan sus bondades para multiples propositos, las abstracciones que estos frameworks proporcionan muchas veces hacen innecesario conocer AOP, pero conocerlo puede traer muchos beneficios para enternder m,ejor las gherramientas e incluso usar sus bondades en nuestras propias aplicaciones

La idea de esta charla es dar los fundamentos de AOP y ejemplos practicos con Spring y Micronaut.

**Comment by benek** [comment]
Impartida en Noviembre de 2023: https://www.youtube.com/live/mpr2AgbGg4E
