### ISSUE TITLE
Concurrencia Estructurada en Java

### ISSUE THREAD

**Issue by domix** [javamexico/propuestas-meetup#95]
La concurrencia estructurada es un modelo de programación que se centra en la gestión de la concurrencia de manera organizada y estructurada. Algunos de sus beneficios incluyen:

1. **Facilidad de comprensión**: La concurrencia estructurada promueve el diseño de programas concurrentes de manera organizada y clara, lo que facilita la comprensión del código para los desarrolladores.

2. **Mayor mantenibilidad**: Al estructurar la concurrencia de manera ordenada, se facilita el mantenimiento del código a lo largo del tiempo, lo que ayuda a reducir la posibilidad de errores y a agilizar el proceso de depuración.

3. **Mayor modularidad**: Permite dividir el código en módulos que pueden ser desarrollados, probados y mantenidos de forma independiente, lo que facilita la colaboración entre equipos de desarrollo.

4. **Mejora del rendimiento**: La concurrencia estructurada puede mejorar el rendimiento de las aplicaciones al permitir la ejecución simultánea de tareas, aprovechando al máximo los recursos disponibles del sistema.

5. **Manejo más eficiente de recursos**: Al utilizar la concurrencia de manera estructurada, es posible gestionar de manera más eficiente los recursos del sistema, evitando bloqueos y optimizando el uso de la CPU y la memoria.

6. **Mejora de la escalabilidad**: Permite diseñar sistemas que puedan escalar de manera eficiente para manejar un mayor número de usuarios o procesos concurrentes sin sacrificar el rendimiento.

En resumen, la concurrencia estructurada ofrece una serie de beneficios que pueden mejorar la calidad, el rendimiento y la mantenibilidad de los sistemas concurrentes.

En esta charla mostraré la nueva API en Java para concurrencia estructurada.

**Comment by benek** [comment]
@domix ¿presencial?

**Comment by domix** [comment]
> @domix ¿presencial?

yo digo que simon @benek

**Comment by josuemb** [comment]
Se lee bastante interesante.

**Comment by ingscjoshua** [comment]
Que se arme!!!!
